### ISSUE TITLE
Issues with enlighter-wp-plugin-integration.md

### ISSUE THREAD

**Issue by westerdaled** [EnlighterJS/docs#1]
Hi 

I am fairly technical ( as I work in IT)  but this baffled me a bit as these instructions seem difficult to follow.

Experimental EnlighterJS3 Integration into Enlighter WordPress Plugin v3
Targeted to advanced users only! I think you mean PHD students!!!

Enlighter Plugin Settings
WordPress Backend -> Enlighter -> Options -> Resources and CDN

Include Enlighter-CSS : DISABLE
Include Enlighter-Javascript : DISABLE
Include External Themes : DISABLE
MooTools Framework Source: "NOT INCLUDE"
Enlighter Config: "NOT INCLUDE"

Q: _In my world, I don't see any wordpress backend so  just /public_html   and beyond .  So none of the above seem obvious in either the Enlighter Options page or when I browse the plugin with FileZilla_ 

Add EnlighterJS3 Resources to your Theme 

_Q:  If you are referring to enlighterjs.min.css  and enlighterjs.min.js , then surely you mean I replace the relevant files in the /resources folder_

-

Upload the enlighterjs resources to your theme and include them.

_Q: again why would I want be  hacking my theme.  I would have thought there is away for the existing Enlighter Plugin to include the files it needs as part of Enlighter3 JS RC1_   

Header Code

    
    <link rel="stylesheet" href="enlighterjs.min.css" />
Footer Code

    
    <script type="text/javascript" src="enlighterjs.min.js"></script>

    
    <script type="text/javascript">
        // special Enlighter Plugin Init Code
        EnlighterJS.init('pre.EnlighterJSRAW', 'code.EnlighterJSRAW');
    </script>
Modify Enlighter Plugin Language+Theme Lists
You have to override the Language + Theme Lists with the current available ones!

_Q:  are you referring to the current version of the Enlighter Plugin? If so a better approach would be to  see dir/file and locate lines xxxx and replace with yyyyy _ 

Themes Languages

**Comment by AndiDittrich** [comment]
Hi Daniel,

thanks for discussing this issue on Github :+1: 

and sorry for that... is should replace "advanced users" with "prof. wordpress/php" developer :(

In the past i've made very bad experience with users who changed/edited the plugin code....therefore i won't use this variant anymore (may break the website  and inexperienced users cannot restore the previous state).

**WordPress Backend**

That's the WordPress Admin Area where you create posts/pages - `yourdomain.tld/wp-admin`
On the left side menu bar there is a menu item called "Enlighter"

**EnlighterJS3 init code**

to add this very small piece of code:

1. you have to modify your theme footer template **OR**
2. add some filter hooks to your themes `functions.php`  **OR**
3. create a custom plugin 

**Integration via Themes**

Currently, i'm refactoring/rewriting the Enlighter WordPress plugin because there **is no easy method** like "changing some files" to add EnlighterJS3. It requires some deeper modifications (init code generation, cache management).

Adding EnlighterJS3 support via a Theme - (static html and/or `functions.php`) is the most easy and reliable way.

If you like a could create a demo ChildTheme based on one of the **twenty-xxxx** standard themes


best regards, Andi

**Comment by AndiDittrich** [comment]
i've created an experimental plugin for you which adds EnlighterJS v3 to the current Enlighter Plugin (fulfills the tasks mentioned in the docs)

https://github.com/EnlighterJS/experiments/tree/master/wp-enlighterjs3-compat

**Comment by westerdaled** [comment]
I have now implemented  the requested changes in Admin->Enlighter-Options-CDN & resources 

I have uploaded wp-enlighterjs3-compat and activated. it .  

I guess the next is to use test out with a post ?

**Comment by AndiDittrich** [comment]
of course. it works fine within my deveopment/testing environment

**Comment by westerdaled** [comment]
Yep .. here - it looks great and not dissimilar to VS code ;-)



https://westerdale.blog/?p=462&shareadraft=baba462_5b5f71299f00a
